name: Build - Windows

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**/README.md"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies for Windows
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install ninja -y
        # Installing Visual Studio Build Tools is optional if Ninja is sufficient
        choco install visualstudio2022-build-tools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional" -y

    - name: Verify Ninja Installation
      run: ninja --version
  
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Ninja"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
