name: Build - Windows

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**/README.md"
      - "**/.github/workflows/build_linux.yml"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**/README.md"
      - "**/.github/workflows/build_linux.yml"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 'latest'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 17 2022" -A x64

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
