name: Build and test CMake project on Linux

on:
  push:
    branches: [ main ]
    pull_requests: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: shallow # To save space, you can choose 'shallow' or 'none' for 'fetch-depth'

      - name: Setup CMake
        uses: cmake/cmake-setup@3.1.4
        with:
          cmake_version: 3.20.X # Update this value to the latest CMake version you want to use (e.g., 3.21.X)
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential git cmake libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

      - name: Build the project
        run: cmake . && cmake --build . --config Release
